name: PHP Continuous integration

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install dependencies
      run: composer install --ignore-platform-reqs
      
    - name: Run unit tests, Code Sniffer,Mess Detector
      run: ./vendor/bin/grumphp run
    
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

